# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-18 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='id',
            field=models.AutoField(db_column=b'ID', primary_key=True, serialize=False),
        ),
    ]
